### ISSUE TITLE
I have installed hexo-wordcount,but I've got a problem with hexo-g

### ISSUE THREAD

**Issue by jerrywcy** [willin/hexo-wordcount#14]
我已经装好了，word.ejs也配置好了，但是generate的时候就显示post not defined
以下是报错信息：
```
ERROR D:\王楚屹\Hexo\jerrywcy.github.io\themes\alpha-dust\layout\post.ejs:15
    13|         </span>
    14|         <section class="main">
 >> 15|             <%- partial('_partial/article-long', {item: page}) %>
    16|         </section>
    17|
    18|     </div>

D:\王楚屹\Hexo\jerrywcy.github.io\themes\alpha-dust\layout\_partial\article-long.ejs:28
    26|         <!-- hexo-wordcount -->
    27|         <% if(true){ %>
 >> 28|             <%- partial('word') %>
    29|         <% } %>
    30|         <!-- Gallery -->
    31|         <% if (item.photos && item.photos.length){ %>

D:\王楚屹\Hexo\jerrywcy.github.io\themes\alpha-dust\layout\_partial\word.ejs:6
    4|         <i class="fa fa-keyboard-o"></i>
    5|         <span class="post-meta-item-text">  字数统计: </span>
 >> 6|         <span class="post-count"><%= wordcount(post.content) %>字</span>
    7|       </span>
    8|     </span>
    9|

post is not defined
ReferenceError: D:\王楚屹\Hexo\jerrywcy.github.io\themes\alpha-dust\layout\post.ejs:15
    13|         </span>
    14|         <section class="main">
 >> 15|             <%- partial('_partial/article-long', {item: page}) %>
    16|         </section>
    17|
    18|     </div>

D:\王楚屹\Hexo\jerrywcy.github.io\themes\alpha-dust\layout\_partial\article-long.ejs:28
    26|         <!-- hexo-wordcount -->
    27|         <% if(true){ %>
 >> 28|             <%- partial('word') %>
    29|         <% } %>
    30|         <!-- Gallery -->
    31|         <% if (item.photos && item.photos.length){ %>

D:\王楚屹\Hexo\jerrywcy.github.io\themes\alpha-dust\layout\_partial\word.ejs:6
    4|         <i class="fa fa-keyboard-o"></i>
    5|         <span class="post-meta-item-text">  字数统计: </span>
 >> 6|         <span class="post-count"><%= wordcount(post.content) %>字</span>
    7|       </span>
    8|     </span>
    9|

post is not defined
    at eval (eval at compile (D:\王楚屹\Hexo\jerrywcy.github.io\node_modules\ejs\lib\ejs.js:633:12), <anonymous>:11:36)
    at returnedFn (D:\王楚屹\Hexo\jerrywcy.github.io\node_modules\ejs\lib\ejs.js:668:17)
    at Object.exports.render (D:\王楚屹\Hexo\jerrywcy.github.io\node_modules\ejs\lib\ejs.js:419:37)
    at Hexo.ejsRenderer (D:\王楚屹\Hexo\jerrywcy.github.io\node_modules\hexo-renderer-ejs\lib\renderer.js:7:14)
    at Render.renderSync (D:\王楚屹\Hexo\jerrywcy.github.io\node_modules\hexo\lib\hexo\render.js:96:22)
    at Theme._View.View._compiledSync (D:\王楚屹\Hexo\jerrywcy.github.io\node_modules\hexo\lib\theme\view.js:126:43)
    at Theme._View.View.View.renderSync (D:\王楚屹\Hexo\jerrywcy.github.io\node_modules\hexo\lib\theme\view.js:48:23)
    at Object.partial (D:\王楚屹\Hexo\jerrywcy.github.io\node_modules\hexo\lib\plugins\helper\partial.js:34:15)
    at eval (eval at compile (D:\王楚屹\Hexo\jerrywcy.github.io\node_modules\ejs\lib\ejs.js:633:12), <anonymous>:49:17)
    at returnedFn (D:\王楚屹\Hexo\jerrywcy.github.io\node_modules\ejs\lib\ejs.js:668:17)
    at Object.exports.render (D:\王楚屹\Hexo\jerrywcy.github.io\node_modules\ejs\lib\ejs.js:419:37)
    at Hexo.ejsRenderer (D:\王楚屹\Hexo\jerrywcy.github.io\node_modules\hexo-renderer-ejs\lib\renderer.js:7:14)
    at Render.renderSync (D:\王楚屹\Hexo\jerrywcy.github.io\node_modules\hexo\lib\hexo\render.js:96:22)
    at Theme._View.View._compiledSync (D:\王楚屹\Hexo\jerrywcy.github.io\node_modules\hexo\lib\theme\view.js:126:43)
    at Theme._View.View.View.renderSync (D:\王楚屹\Hexo\jerrywcy.github.io\node_modules\hexo\lib\theme\view.js:48:23)
    at Object.partial (D:\王楚屹\Hexo\jerrywcy.github.io\node_modules\hexo\lib\plugins\helper\partial.js:34:15)
    at eval (eval at exports.compile (D:\王楚屹\Hexo\jerrywcy.github.io\node_modules\hexo-renderer-mathjax\node_modules\ejs\lib\ejs.js:242:14), <anonymous>:30:707)
    at eval (eval at exports.compile (D:\王楚屹\Hexo\jerrywcy.github.io\node_modules\hexo-renderer-mathjax\node_modules\ejs\lib\ejs.js:242:14), <anonymous>:30:808)
    at D:\王楚屹\Hexo\jerrywcy.github.io\node_modules\hexo-renderer-mathjax\node_modules\ejs\lib\ejs.js:255:15
    at Object.exports.render (D:\王楚屹\Hexo\jerrywcy.github.io\node_modules\hexo-renderer-mathjax\node_modules\ejs\lib\ejs.js:293:13)
    at Hexo.<anonymous> (D:\王楚屹\Hexo\jerrywcy.github.io\node_modules\hexo-renderer-mathjax\index.js:14:24)
    at Hexo.tryCatcher (D:\王楚屹\Hexo\jerrywcy.github.io\node_modules\bluebird\js\release\util.js:16:23)
```
但是我页面底部的全站字数统计是正常的
一加上这个整个文章页面就都空白了。
```html
<html>
        <head></head>
        <body></body>
</html>
```
所有文章的html文件都长这样
大佬帮帮忙！

**Comment by willin** [comment]
你的文章变量不叫post，传啥用啥，换item试试。

**Comment by jerrywcy** [comment]
好了，谢谢大佬！
