### ISSUE TITLE
Issue with 'use strict'

### ISSUE THREAD

**Issue by starkshaw** [willin/hexo-wordcount#6]
When use with theme Next, texting the site locally by using `hexo s`, it gives the error as follows:
```
ERROR Plugin load failed: hexo-wordcount
/path/to/hexo/site/node_modules/hexo-wordcount/index.js:17
  'use strict';
  ^^^^^^^^^^^^

SyntaxError: Illegal 'use strict' directive in function with non-simple parameter list
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
...
```

And none of word count and time to read is working.

**Comment by willin** [comment]
try v3.0.1

**Comment by starkshaw** [comment]
New Error:
```
Unhandled rejection TypeError: readingTime.format is not a function
    at Object.<anonymous> (/path/to/hexo/folder/node_modules/hexo-wordcount/index.js:19:54)
    at wrapper (/path/to/hexo/folder/node_modules/lodash/lodash.js:4968:19)
    at Object._ctx.post_template.render (eval at precompile (/path/to/hexo/folder/node_modules/swig/lib/swig.js:498:13), <anonymous>:282:123)
    at eval (eval at precompile (/path/to/hexo/folder/node_modules/swig/lib/swig.js:498:13), <anonymous>:805:1078)
    at Object.exports.each (/path/to/hexo/folder/node_modules/swig/lib/utils.js:45:11)
    at eval (eval at precompile (/path/to/hexo/folder/node_modules/swig/lib/swig.js:498:13), <anonymous>:798:10)
    at Object.eval [as tpl] (eval at precompile (/path/to/hexo/folder/node_modules/swig/lib/swig.js:498:13), <anonymous>:813:3)
    at compiled (/path/to/hexo/folder/node_modules/swig/lib/swig.js:619:18)
    at Theme._View.View._compiled (/path/to/hexo/folder/node_modules/hexo/lib/theme/view.js:127:30)
    at Theme._View.View.View.render (/path/to/hexo/folder/node_modules/hexo/lib/theme/view.js:29:15)
    at /path/to/hexo/folder/node_modules/hexo/lib/hexo/index.js:390:25
    at tryCatcher (/path/to/hexo/folder/node_modules/bluebird/js/release/util.js:16:23)
    at /path/to/hexo/folder/node_modules/bluebird/js/release/method.js:15:34
    at RouteStream._read (/path/to/hexo/folder/node_modules/hexo/lib/hexo/router.js:134:3)
    at RouteStream.Readable.read (_stream_readable.js:429:10)
    at resume_ (_stream_readable.js:809:12)
    at _combinedTickCallback (internal/process/next_tick.js:102:11)
    at process._tickCallback (internal/process/next_tick.js:161:9)
```
