### ISSUE TITLE
Load Failed

### ISSUE THREAD

**Issue by hwding** [willin/hexo-wordcount#8]
Using:
- hexo: 3.3.8
- hexo-cli: 1.0.3
- os: Linux 4.10.0-32-generic linux x64
- http_parser: 2.7.0
- node: 4.7.2
- v8: 4.5.103.43
- uv: 1.9.1
- zlib: 1.2.8
- ares: 1.10.1-DEV
- icu: 57.1
- modules: 46
- openssl: 1.0.2g

Theme: next

Output:

```
➜  content node_modules/hexo/bin/hexo g
ERROR Plugin load failed: hexo-wordcount
SyntaxError: Unexpected token {
    at Object.exports.runInThisContext (vm.js:53:16)
    at /home/hwding/Work/blog/content/node_modules/hexo/lib/hexo/index.js:230:17
    at tryCatcher (/home/hwding/Work/blog/content/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/hwding/Work/blog/content/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/home/hwding/Work/blog/content/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/home/hwding/Work/blog/content/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/home/hwding/Work/blog/content/node_modules/bluebird/js/release/promise.js:693:18)
    at Promise._fulfill (/home/hwding/Work/blog/content/node_modules/bluebird/js/release/promise.js:638:18)
    at Promise._resolveCallback (/home/hwding/Work/blog/content/node_modules/bluebird/js/release/promise.js:432:57)
    at Promise._settlePromiseFromHandler (/home/hwding/Work/blog/content/node_modules/bluebird/js/release/promise.js:524:17)
    at Promise._settlePromise (/home/hwding/Work/blog/content/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/home/hwding/Work/blog/content/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/home/hwding/Work/blog/content/node_modules/bluebird/js/release/promise.js:693:18)
    at Promise._fulfill (/home/hwding/Work/blog/content/node_modules/bluebird/js/release/promise.js:638:18)
    at /home/hwding/Work/blog/content/node_modules/bluebird/js/release/nodeback.js:42:21
    at /home/hwding/Work/blog/content/node_modules/graceful-fs/graceful-fs.js:78:16
INFO  Start processing
INFO  Files loaded in 593 ms
INFO  0 files generated in 691 ms
```

**Comment by willin** [comment]
do you install the plugin properly via npm/yarn?

**Comment by hwding** [comment]
Not quite sure, it gave me warnings.

```
➜  content npm i --save hexo-wordcount
hexo-site@0.0.0 /home/hwding/Work/blog/content
└─┬ hexo-wordcount@3.0.2 
  ├─┬ html-to-text@2.1.3 
  │ ├── he@1.1.1 
  │ ├── htmlparser@1.7.7 
  │ ├── underscore@1.8.3 
  │ └── underscore.string@3.3.4 
  ├── numeral@1.5.6 
  └─┬ wordcount@1.1.1 
    └─┬ match-words@0.1.1 
      └── word-regex@0.1.2 

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.1.2
```

**Comment by willin** [comment]
i did not use fsevents, bluebird or graceful-fs in this project

**Comment by hwding** [comment]
May be the compatibility issue with hexo or hexo-theme.

**Comment by willin** [comment]
can you provide a demo project, and i'll look into it?

**Comment by hwding** [comment]
Site is under construction.  
You can `hexo init` and switch to theme [next](https://github.com/iissnan/hexo-theme-next), then install the plugin.

**Comment by willin** [comment]
checkout this project: 

https://github.com/WulianCC/WulianCC.github.io/blob/source/themes/next/layout/_macro/sidebar.swig#L45

**Comment by hwding** [comment]
## Debug
Print generated codes around where the exception is thrown in *hexo/index.js*.

```javascript
script = '(function(exports, require, module, __filename, __dirname, hexo){' +
      script + '});';
try {
  var fn = vm.runInThisContext(script, path);
} catch (e) {
  console.log(script);
}
```
Found the error is caused by:

```javascript
hexo.extend.helper.register('min2read', function (content, { cn = 300, en = 160 } = {}) {
    var len = counter(content);
    var readingTime = len[0] / cn + len[1] / en;
    return readingTime < 1 ? '1' : numeral(readingTime).format('0');
});
```
## Cause
Node.js 4.7.2 does not support default parameters' deconstruction.

## Solution
Upgrade to node 6 or 8.

**Comment by willin** [comment]
why? when i write this plugin node.js tls is 4.7.0

**Comment by hwding** [comment]
No idea, node just told me the `{` in `function (content, { cn = 300, en = 160 } = {})` is unexpected, and after I upgraded node, it turns out all fine.
